version: "3"

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PETERdinis1234
      POSTGRES_DB: spstapp
    ports:
      - "3306:5432"
    restart: always